language: android
sudo: false
jdk: oraclejdk8

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-25.0.2
  - echo y | android update sdk -u -a -t android-25
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=25.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes



android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
 - build-tools-23.0.1
 - android-24
 - android-23
 - android-22
 - sys-img-armeabi-v7a-android-22
 - extra-android-support
 - extra-android-m2repository
 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+



notifications:
  email: false

before_deploy:
- cp $TRAVIS_BUILD_DIR/example_keystore.jks $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/example_keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk ExampleKeystoreAlias
# Verification
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/25.0.2/zipalign -v 4 app-release-unsigned.apk TakeHomeAPK.apk"

deploy:
  provider: releases
  file: TakeHomeAPK.apk
  skip_cleanup: true
  on:
    repo: take-home/maxi_takecoursequiz
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZNi10cLA+B5aMjF3IZ3cDPEa4pcF08uVpkqrscsUADrt62YFnMoyBcH3Kv7Yf2L/7P6hUndbMJ3heh/yRdJ8npYE64AA1k4aBzD6MbivbtWJk8aK12ddEqSiFqVCc1oAb0MDfMk/fBFV43JijS6+UuZYqUfUzYyaNe+Obd91hrtjHxyYTeaWa7cG7Sg2KE8dKriSkKCxcPToDWovnbbU+5S7Z4dj0UiTcah+1VWNCkDyoGaocGjx9TxzEBo4LNn2TGTODp6+knuOaklllXZvuf6iozyRb7LROXMH//8DnmxRIs7I3C8strQH6dBQEXfB6QpoqyshTLhxYlfMSLaQ/ leonardmensah@Leonards-MBP-2.local.tld"